routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FormController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('forms', FormController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use App\Services\JsonRpcClient;
use Illuminate\Http\RedirectResponse;
use App\Http\Requests\FormStoreRequest;
use Illuminate\Contracts\Support\Renderable;

class FormController extends Controller
{
    const
        METHOD_INDEX = 'form_index',
        METHOD_STORE = 'form_store',
        METHOD_SHOW  = 'form_show'
    ;

    /**
     * @var JsonRpcClient
     */
    protected $service;

    /**
     * FormController constructor.
     *
     * @param JsonRpcClient $service
     */
    public function __construct(JsonRpcClient $service)
    {
        $this->service = $service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Renderable
     */
    public function index()
    {
        $data = collect($this->service->send(self::METHOD_INDEX));

        if (! $data->has('result')) {
            abort(500, 'Server error!');
        }

        $forms = collect($data->get('result'))
            ->map(function (array $form) {
                return collect($form);
            });

        return view('forms.index', compact('forms'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create()
    {
        return view('forms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param FormStoreRequest $request
     * @return RedirectResponse
     */
    public function store(FormStoreRequest $request)
    {
        $data = collect(
            $this->service->send(self::METHOD_STORE, $request->validated())
        );

        if (! $data->has('result')) {
            abort(500, 'Server error');
        }

        return response()->redirectToRoute('forms.index')->with('success', 'Form Stored!');
    }

    /**
     * Display the specified resource.
     *
     * @param string $page_uid
     * @return Renderable
     */
    public function show(string $page_uid)
    {
        $data = collect(
            $this->service->send(self::METHOD_SHOW, ['page_uid' => $page_uid])
        );

        if (! $data->has('result')) {
            abort(404, 'Form not found!');
        }

        return view('forms.show', ['form' => collect($data->get('result'))]);
    }
}

resources/views/forms/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Store Form</div>

                <div class="card-body">
                    <form method="post" action="{!! route('forms.store') !!}">
                        <div class="form-row">
                            <div class="col">
                                <label for="page_uid" class="sr-only">Page UID</label>
                                <input type="text" class="form-control" id="page_uid" name="page_uid"
                                       placeholder="Enter page_uid" value="{{ request('page_uid', uniqid()) }}"
                                       required>
                            </div>
                            <div class="col">
                                <label for="name" class="sr-only">Name</label>
                                <input type="text" class="form-control" id="name" name="name"
                                       placeholder="Enter name"
                                       value="{{ request('name') }}" required>
                            </div>
                        </div>

                        <div class="form-row mt-3">
                            <div class="col">
                                <label for="email" class="sr-only">Email</label>
                                <input type="email" class="form-control" id="email" name="email"
                                       placeholder="Enter email" value="{{ request('name') }}" required>
                            </div>
                            <div class="col">
                                <label for="phone" class="sr-only">Phone</label>
                                <input type="tel" class="form-control" id="phone" name="phone"
                                       placeholder="Enter phone" value="{{ request('name') }}" required>
                            </div>
                        </div>

                        <div class="form-row  mt-3">
                            <div class="col">
                                <button type="submit" class="btn btn-success">Store</button>
                                <a href="{{ URL::previous() }}" class="btn btn-primary  ml-1">Back</a>
                            </div>
                        </div>
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forms/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Forms</div>

                <a href="{!! route('forms.create') !!}" class="btn btn-success col-md-2 mx-sm-3 mt-3">Create</a>

                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Page UID</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($forms as $form)
                            <tr>
                                <td>{{ $form->get('page_uid') }}</td>
                                <td>{{ $form->get('name') }}</td>
                                <td>{{ $form->get('phone') }}</td>
                                <td>{{ $form->get('email') }}</td>
                                <td>
                                    <a href="{!! route('forms.show', [$form->get('page_uid')]) !!}"
                                       class="btn btn-primary">Show</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5">
                                    Forms not found
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/forms/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Show Form</div>

                <div class="card-body">
                    <div class="form-row">
                        <div class="col">
                            <label for="page_uid" class="sr-only">Page UID</label>
                            <input type="text" class="form-control" id="page_uid" name="page_uid"
                                   value="{{ $form->get('page_uid') }}" readonly>
                        </div>
                        <div class="col">
                            <label for="name" class="sr-only">Name</label>
                            <input type="text" class="form-control" id="name" name="name"
                                   value="{{ $form->get('name') }}" readonly>
                        </div>
                    </div>

                    <div class="form-row mt-3">
                        <div class="col">
                            <label for="email" class="sr-only">Email</label>
                            <input type="email" class="form-control" id="email" name="email"
                                   value="{{ $form->get('email') }}" readonly>
                        </div>
                        <div class="col">
                            <label for="phone" class="sr-only">Phone</label>
                            <input type="tel" class="form-control" id="phone" name="phone"
                                   value="{{ $form->get('phone') }}" readonly>
                        </div>
                    </div>

                    <div class="form-row  mt-3">
                        <div class="col">
                            <a href="{{ URL::previous() }}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,400,600,900" rel="stylesheet">

    <!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
<div id="app">
    <main class="py-4">
        <div class="container mt-3 mb-3">
            @include('vendor.message')

            @yield('content')
        </div>
    </main>
</div>
</body>
</html>